### ISSUE TITLE
[ep6-security][user-plain-password]

### ISSUE THREAD

**Issue by Arman-Hosseini** [knpuniversity/symfony#37]
> Inside setPlainPassword(), do one more thing: $this->password = null:

If we have a **change password form** and if the user enters their **current password** with the new password - then the password will not be changed and the session and user authentication will be violated due to `$password = null`.

**Comment by Arman-Hosseini** [comment]
It is not possible to compare the current password of the user with what entered using [this](https://symfony.com/doc/3.4/reference/constraints/UserPassword.html) method.

**Comment by Arman-Hosseini** [comment]
But it can be done with `UserPasswordEncoderInterface::isPasswordValid` before submitting the form.

It should be added as a note.

**Comment by Arman-Hosseini** [comment]
Checking the user's current password with what entered before submitting the form - even with the `UserPasswordEncoderInterface::isPasswordValid` method is not possible.

**Comment by weaverryan** [comment]
Hi @Arman-Hosseini!

I believe you're referring to the Symfony 3 security tutorial? https://symfonycasts.com/screencast/symfony3-security/user-plain-password

Yea, I agree - I don't like this method of encoding the plain password anymore (via a listener) - it's just too magic and error prone. In the Symfony4 tutorials, we do it by making `plainPassword` an unmapped field on the form instead of overriding the hashed password property on the entity.

I'm going to close this issue because it's about an old, Symfony 3 tutorial. But if you have any other comments or questions, let me know :).

Cheers!

**Comment by Arman-Hosseini** [comment]
Hi @weaverryan :)
Yes this is an old tutorial, but Symfony 3.4 is a long-term support version, and given that many people use it - so it may need to be mentioned as a reminder.

**Comment by weaverryan** [comment]
Hey @Arman-Hosseini!

> Yes this is an old tutorial, but Symfony 3.4 is a long-term support version

That's true. But to manage our workload, we usually only add notes to existing tutorials that address a specific bug. This, unfortunately, would require a bigger change and the problem only affects some situations (like the validator you mentioned). So, we "fix" this by showing it better in more update-to-date tutorials :).

Cheers!
